spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      # 需要替换为你自己的 key
      api-key: sk-03927e64d0404686aaa3e58850d9805c
      chat:
        option:
          model: qwq-plus
datasource:
  url: jdbc:mysql://rm-cn-bpl4rffho0001v4o.rwlb.rds.aliyuncs.com:5432/ai_agent
  username: my_user
  password: Hzx666...